### ISSUE TITLE
运行geo_engine文件时报错，是mongoengine版本问题引起的吗？

### ISSUE THREAD

**Issue by vincentnull** [convexwf/geo-inverse-query#1]
root@fca4fb89e24a:/app# python3 geo_engine.py --import_geo_data
Traceback (most recent call last):
  File "/app/geo_engine.py", line 16, in <module>
    from mongoengine import (
  File "/usr/local/lib/python3.10/site-packages/mongoengine/__init__.py", line 2, in <module>
    from mongoengine import (
  File "/usr/local/lib/python3.10/site-packages/mongoengine/connection.py", line 5, in <module>
    from pymongo.database import _check_name
ImportError: cannot import name '_check_name' from 'pymongo.database' (/usr/local/lib/python3.10/site-packages/pymongo/database.py)

**Comment by convexwf** [comment]
有可能，可以看看 requirement.txt ，mongoengine==0.28.2

**Comment by convexwf** [comment]
在最新的提交里已经修复了这个问题，`requirements.txt` 里增加了对 pymongo 版本的说明。
